name: clothesshop
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  badges: ^3.1.2
  sliding_clipped_nav_bar: ^3.1.1
  fan_carousel_image_slider: ^1.0.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  http: ^1.2.2

  internet_connection_checker: ^2.0.0
  path_provider: ^2.1.4
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
